name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+"
  pull_request:

permissions:
  contents: write

jobs:

  test:
    strategy:
      matrix:
        - node-version: ["14", "16", "18"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  build:
    if: ${{ startsWith('/refs/tags/v', github.ref) }}
    needs: test
    strategy:
      matrix:
        - node-version: ["14", "16", "18"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Setup artifact cache
        uses: actions/cache@v3
        with:
          path: heroku-nodejs-plugin
          key: heroku-nodejs-plugin-${{ matrix.node-version }}-${{ github.run_id }}
      - name: Build plugin
        run: npm run build

  release:
    if: ${{ startsWith('/refs/tags/v', github.ref) }}
    needs: build
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Create release
        run: "./scripts/create-release.sh"

  upload:
    if: ${{ startsWith('/refs/tags/v', github.ref) }}
    needs: release
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        - node-version: ["14", "16", "18"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore artifact cache
        uses: actions/cache@v3
        with:
          key: heroku-nodejs-plugin-${{ matrix.node-version }}-${{ github.run_id }}
      - name: Upload artifact
        run: "./scripts/upload-assets.sh ${{ matrix.node-version }}"
